"use strict";

window.addEventListener("load", function () {
  console.log("Patching Orca <--> Enfer!");

  const orcaClient = document.getElementById("orca-iframe").contentWindow
    .orcaClient;
  const enferClient = document.getElementById("enfer-iframe").contentWindow
    .enferClient;

  const enferBridge = {
    send: (msg) => {
      enferClient.io.onMessage({ data: msg });
    },
    name: "enferBridge",
  };

  orcaClient.io.midi.outputDevice = () => enferBridge;

  window.orcaClient = orcaClient;
  window.enferClient = enferClient;

});

const examples = {
  simpleBeat: `
.............
.............
....D4.......
.....:00cf...
.............
...5U8.......
....*:00a3...
.............
...2U4.......
.....:00g5...
.............
...2D8.......
.....:00hf...
.............
....D........
.....:10e....
.............
.............
`
}

function loadExample(name) {
  orcaClient.orca.reset();
  orcaClient.orca.writeBlock(10, 10, examples[name])
}